services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    networks:
      - simone-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: "mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongodb:27017/"
      ME_CONFIG_BASICAUTH: false
    networks:
      - simone-network

  maildev:
    image: maildev/maildev
    ports:
      - 1080:1080  # Web UI
      - 1025:1025  # SMTP server
    networks:
      - simone-network

  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 8900:8900
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: 'minio server /data/minio --console-address ":8900"'
    volumes:
      - miniodata:/data/minio
    networks:
      - simone-network

volumes:
  mongodbdata:
  miniodata:

networks:
  simone-network:
